
contexts:
  buildenv:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -w
        - /app
        - russellseymour/stacks-pwsh-golang:1.16.11
        - pwsh
        - -NoProfile
        - -Command

  inttestenv:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -w
        - /app
        - russellseymour/dotnet-git:6
        - pwsh
        - -NoProfile
        - -Command        

  docsenv:
    executable:
      bin: docker
      args:
        - run
        - --rm
        - -v
        - ${PWD}:/app
        - -w
        - /app
        - russellseymour/pandoc-asciidoctor
        - pwsh
        - -NoProfile
        - -Command        

tasks:

  buildnumber:
    context: buildenv
    command:
      - /app/build/scripts/Set-BuildNumber.ps1 -number $BUILDNUMBER
    exportAs: BUILDNUMBER

  clean:
    description: Clean old builds
    command:
      - rm -rf outputs

  _compile:
    description: Compile CLI and Integration Tests
    context: buildenv
    command:
      - /app/build/scripts/Invoke-Compile.ps1 -BuildNumber $BUILDNUMBER

  _docs:
    description: Build Docs for Stacks CLI
    context: docsenv
    command:
      - /app/build/scripts/Build-Docs.ps1 -BuildNumber $BUILDNUMBER -BasePath /app

  docs:pdf:
    context: docsenv
    description: Generate PDF documentation
    command:
      - mkdir -p outputs/docs/pdf
      - asciidoctor-pdf -a pdf-theme=/app/docs/styles/theme.yml -a pdf-fontsdir="/app/docs/styles/fonts;GEM_FONTS_DIR" -a doctype="book" -a stackscli_version="${BUILDNUMBER}" -o "Stacks CLI Manual - ${BUILDNUMBER}.pdf" -a toc -D /app/outputs/docs/pdf /app/docs/manual.adoc

  docs:markdown:
    context: docsenv
    description: Create Markdown docs
    command:
      - mkdir -p outputs/docs/md
      - /app/build/scripts/ConvertTo-Markdown.ps1 -docs_dir /app/docs -output_dir /app/outputs/docs/md

  test:unit:
    context: buildenv
    description: Run Unit Tests
    command:
      - /app/build/scripts/Invoke-UnitTests.ps1

  test:int:
    context: inttestenv
    description: Run Integration Tests
    
    command:
      - /app/build/scripts/Invoke-IntegrationTests.ps1 -build_number $BUILDNUMBER -RunTests

  test:int:generate_report:
    context: buildenv
    command:
      - /app/build/scripts/Invoke-IntegrationTests.ps1 -build_number $BUILDNUMBER -Report

  _release:
    context: buildenv
    command:
      - /app/build/scripts/Publish-GitHubRelease.ps1 -version $VERSION_NUMBER -commitId $API_KEY -artifactsDir $ARTIFACTS_DIR -Owner $OWNER

pipelines:

  build:
    - task: clean
    - task: buildnumber
    - task: _docs
      depends_on: 
        - clean
        - buildnumber
    - task: test:unit
      depends_on: clean
    - task: _compile
      depends_on:
        - clean
        - buildnumber

  docs:
    - task: buildnumber
    - task: _docs
      depends_on: buildnumber

  inttest:
    - task: buildnumber
    - task: test:int
      depends_on: buildnumber
    - task: test:int:generate_report
      depends_on: test:int

  compile:
    - task: buildnumber
    - task: _compile
      depends_on: buildnumber

  release:
    - task: buildnumber
    - task: _release
      depends_on:
        - buildnumber
      env:
        VERSION_NUMBER: $BUILDNUMBER
        API_KEY: $GITHUB_TOKEN
        NOTES:
        COMMIT_ID: $COMMIT_ID
        ARTIFACTS_DIR: $ARTIFACTS_DIR    