stacks:
  dotnet:
    webapi: 
      url: https://github.com/amido/stacks-dotnet
      trunk: master
    cqrs: 
      url: https://github.com/amido/stacks-dotnet-cqrs
      trunk: master
    events: 
      url: https://github.com/amido/stacks-dotnet-cqrs-events
      trunk: master
  java:
    webapi:
      url: https://github.com/amido/stacks-java
      trunk: master
    cqrs:
      url: https://github.com/amido/stacks-java-cqrs
      trunk: main
    events:
      url: https://github.com/amido/stacks-java-cqrs-events
      trunk: main
  nodejs:
    csr: 
      url: https://github.com/amido/stacks-typescript-csr
      trunk: master
    ssr:
      url: https://github.com/amido/stacks-typescript-ssr
      trunk: master
  infra:
    aks: 
      url: https://github.com/amido/stacks-infrastructure-aks/
      trunk: master