frameworks:
  - name: dotnet
    commands:
      - dotnet
      - git
    version:
      command: dotnet
      arguments: --version
      pattern: (?P<version>.*)

  - name: java
    commands:
      - java
      - git
      - mvn
    version:
      command: java
      arguments: -version
      pattern: '"(?P<version>.*)"'

  - name: nx
    commands:
      - node
      - npx
      - git
    version:
      command: node
      arguments: --version
      pattern: '"v(?P<version>.*)"'

  - name: infra
    commands:
      - git

stacks:
  components:
    - group: dotnet
      name: webapi
      package:
        name: Amido.Stacks.Templates
        type: nuget
        id: stacks-dotnet

    - group: dotnet
      name: cqrs
      package:
        name: Amido.Stacks.CQRS.Templates
        type: nuget
        id: stacks-dotnet-cqrs

    - group: java
      name: webapi
      package:
        url: https://github.com/amido/stacks-java
        version: master
        type: git

    - group: java
      name: cqrs
      package:
        url: https://github.com/amido/stacks-java-cqrs
        version: main
        type: git

    - group: java
      name: events
      package:
        url: https://github.com/amido/stacks-java-cqrs-events
        version: main
        type: git

    - group: nx
      name: next
      package:
        url: https://github.com/amido/stacks-nx
        version: main
        type: git

    - group: nx
      name: apps
      package:
        url: https://github.com/amido/stacks-nx
        version: main
        type: git

    - group: infra
      name: aks
      package:
        url: https://github.com/amido/stacks-infrastructure-aks/
        version: master
        type: git

help:
  root: "https://stacks.amido.com/docs/stackscli/usage"
  scaffold: "https://stacks.amido.com/docs/stackscli/runtime_config#scaffold-options"
  interactive: "https://stacks.amido.com/docs/stackscli/runtime_config#interactive-options"
  version: "https://stacks.amido.com/docs/stackscli/runtime_config#version-options"
  export: "https://stacks.amido.com/docs/stackscli/runtime_config#export-options"

commands:
  git:
    - git init
    - git remote add origin {{ .Project.SourceControl.URL }}
